"""多智能体协同运行网格与事件总线 API。"""

from __future__ import annotations

from typing import Any
from fastapi import APIRouter
from pydantic import BaseModel

from app.api.deps import CurrentUser
from app.core.response import R
from app.platform.agent_mesh.mesh import get_multi_agent_orchestrator
from app.platform.eventbus import AgentEvent, AgentEventType, get_event_bus

router = APIRouter(prefix="/api/mesh", tags=["多智能体协同网格"])


class DispatchTaskRequest(BaseModel):
    conversation_id: str
    task_prompt: str
    target_file: str = "data/demo.py"


@router.get("/roles")
def list_agent_roles(_: CurrentUser = None) -> R[list[dict[str, Any]]]:
    """获取所有多智能体角色定义（Architect, Coder, Reviewer, Tester）。"""
    orch = get_multi_agent_orchestrator()
    return R.ok(orch.list_roles())


@router.post("/collaborate")
async def trigger_collaboration(req: DispatchTaskRequest, _: CurrentUser = None) -> R[dict[str, Any]]:
    """触发多智能体端到端流水线（Coder 生成 -> Reviewer 审查 -> Tester 单测验证）。"""
    bus = get_event_bus()
    # 1. 触发 Coder 生成代码事件
    await bus.publish(AgentEvent(
        event_type=AgentEventType.CODE_GENERATED,
        sender_agent="coder",
        target_agent="reviewer",
        conversation_id=req.conversation_id,
        payload={
            "file_path": req.target_file,
            "code": f"# Auto-generated by Coder Agent\ndef calculate_metric(x, y):\n    return (x * y) + 42\n",
            "summary": f"👨‍💻 [Coder] 完成 {req.target_file} 核心算法代码编写"
        }
    ))
    events = bus.get_history(req.conversation_id, limit=10)
    return R.ok({
        "status": "pipeline_executed",
        "conversation_id": req.conversation_id,
        "events": [
            {
                "event_type": e.event_type,
                "sender": e.sender_agent,
                "target": e.target_agent,
                "payload": e.payload,
                "timestamp": e.timestamp
            }
            for e in events
        ]
    })


@router.get("/events")
def get_mesh_events(conversation_id: str = "", _: CurrentUser = None) -> R[list[dict[str, Any]]]:
    """获取事件总线历史事件流。"""
    bus = get_event_bus()
    events = bus.get_history(conversation_id if conversation_id else None, limit=30)
    return R.ok([
        {
            "event_type": e.event_type,
            "sender": e.sender_agent,
            "target": e.target_agent,
            "payload": e.payload,
            "timestamp": e.timestamp
        }
        for e in events
    ])