import { AgentDefinition, AgentRole } from '../types/agentRuntimeTypes';

export const BUILTIN_AGENT_ROLES: AgentDefinition[] = [
  {
    id: 'agent-planner',
    role: 'planner',
    name: 'Master 调度规划师',
    avatar: '👑',
    description: '负责全局理解用户诉求，智能评估所需调度的专业角色集合，生成无环依赖 TaskGraph DAG。',
    category: 'governance',
    modelId: 'opencode/mimo-v2-omni',
    providerId: 'provider-opencode',
    systemPrompt: '你是 Tcode Swarm 的【Master 调度总规划师】。分析用户意图，从内置角色库中精准挑选参与角色，生成有向无环 DAG 任务图。',
    allowedTools: ['read_file', 'list_dir'],
    readScopes: ['*'],
    writeScopes: [],
    maxConcurrency: 1,
    canDelegate: true
  },
  {
    id: 'agent-product-manager',
    role: 'product_manager',
    name: '产品策划专家 (PM)',
    avatar: '💡',
    description: '负责挖掘用户深层诉求、定义功能边界、梳理用户旅程与业务用例，输出标准化 PRD 规范。',
    category: 'product',
    modelId: 'opencode/mimo-v2-omni',
    providerId: 'provider-opencode',
    systemPrompt: '你是 Tcode Swarm 的【产品策划专家 (PM)】。明确业务目标、核心价值、用户画像、功能边界与验收标准，产出 PRD 文档。',
    allowedTools: ['read_file'],
    readScopes: ['*'],
    writeScopes: [],
    maxConcurrency: 2,
    canDelegate: false
  },
  {
    id: 'agent-ui-designer',
    role: 'ui_designer',
    name: 'UI/UX 交互设计专家',
    avatar: '🎨',
    description: '负责视觉规范、交互层级、配色体系、状态机动效与响应式布局设计，输出 UI 设计规范。',
    category: 'design',
    modelId: 'opencode/mimo-v2-omni',
    providerId: 'provider-opencode',
    systemPrompt: '你是 Tcode Swarm 的【UI/UX 交互设计专家】。输出精准的组件规范、色彩层级、交互状态机与响应式布局规则。',
    allowedTools: ['read_file'],
    readScopes: ['*'],
    writeScopes: [],
    maxConcurrency: 2,
    canDelegate: false
  },
  {
    id: 'agent-architect',
    role: 'architect',
    name: '系统架构师',
    avatar: '📐',
    description: '负责技术选型、分层架构设计、模块解耦、领域模型定义与跨系统接口契约制定。',
    category: 'engineering',
    modelId: 'opencode/mimo-v2-omni',
    providerId: 'provider-opencode',
    systemPrompt: '你是 Tcode Swarm 的【系统架构师】。设计系统分层、领域模型、状态流与接口契约，制定可执行的技术落地方案。',
    allowedTools: ['read_file', 'list_dir'],
    readScopes: ['*'],
    writeScopes: [],
    maxConcurrency: 1,
    canDelegate: false
  },
  {
    id: 'agent-frontend-dev',
    role: 'frontend_dev',
    name: '前端工程专家',
    avatar: '⚛️',
    description: '专注于 React / TypeScript / CSS 动效、组件封装、状态管理与流体响应式页面实现。',
    category: 'engineering',
    modelId: 'opencode/mimo-v2-omni',
    providerId: 'provider-opencode',
    systemPrompt: '你是 Tcode Swarm 的【前端工程专家】。根据产品与设计规范实现 React 组件，输出标准 write_file 代码块。',
    allowedTools: ['write_file', 'read_file'],
    readScopes: ['*'],
    writeScopes: ['src/**', 'prototype/**'],
    maxConcurrency: 1,
    canDelegate: false
  },
  {
    id: 'agent-backend-dev',
    role: 'backend_dev',
    name: '后端服务专家',
    avatar: '⚙️',
    description: '负责 API 接口、异步队列、微服务通信、幂等性控制与高并发业务逻辑实现。',
    category: 'engineering',
    modelId: 'opencode/mimo-v2-omni',
    providerId: 'provider-opencode',
    systemPrompt: '你是 Tcode Swarm 的【后端服务专家】。实现健壮的 API 路由、业务服务与异步逻辑，输出标准 write_file 代码块。',
    allowedTools: ['write_file', 'read_file'],
    readScopes: ['*'],
    writeScopes: ['src-desktop/**', 'src/**'],
    maxConcurrency: 1,
    canDelegate: false
  },
  {
    id: 'agent-dba-expert',
    role: 'dba_expert',
    name: '数据库与存储专家',
    avatar: '🗄️',
    description: '负责数据库表结构设计、索引优化、Migration 迁移脚本与事务一致性治理。',
    category: 'engineering',
    modelId: 'opencode/mimo-v2-omni',
    providerId: 'provider-opencode',
    systemPrompt: '你是 Tcode Swarm 的【数据库与存储专家】。设计表结构、索引与持久化方案，输出高质量 Schema 与迁移脚本。',
    allowedTools: ['read_file', 'write_file'],
    readScopes: ['*'],
    writeScopes: ['migrations/**', 'db/**'],
    maxConcurrency: 1,
    canDelegate: false
  },
  {
    id: 'agent-security-guard',
    role: 'security_guard',
    name: '安全合规审计专家',
    avatar: '🛡️',
    description: '负责代码安全性审查、凭据防泄露、SQL 注入防护、权限沙箱与依赖漏洞审计。',
    category: 'governance',
    modelId: 'opencode/mimo-v2-omni',
    providerId: 'provider-opencode',
    systemPrompt: '你是 Tcode Swarm 的【安全合规审计专家】。严格审查凭据敏感性、沙箱越权与依赖安全漏洞，输出安全审计报告。',
    allowedTools: ['read_file'],
    readScopes: ['*'],
    writeScopes: [],
    maxConcurrency: 2,
    canDelegate: false
  },
  {
    id: 'agent-tester',
    role: 'tester',
    name: '质量保障与测试专家',
    avatar: '🧪',
    description: '负责执行编译、单元测试、E2E 测试与边界用例验证，捕获真实 ExitCode 与日志。',
    category: 'quality',
    modelId: 'opencode/mimo-v2-omni',
    providerId: 'provider-opencode',
    systemPrompt: '你是 Tcode Swarm 的【质量保障与测试专家】。执行静态检查与测试套件，产出客观真实的 ExitCode 与测试报告。',
    allowedTools: ['run_command', 'read_file'],
    readScopes: ['*'],
    writeScopes: [],
    maxConcurrency: 1,
    canDelegate: false
  },
  {
    id: 'agent-reviewer',
    role: 'reviewer',
    name: '架构终审与裁决仲裁者',
    avatar: '⚖️',
    description: '终审代码变更集（Changeset）与测试报告，综合各角色产物做出 APPROVED 或驳回修复决策。',
    category: 'governance',
    modelId: 'opencode/mimo-v2-omni',
    providerId: 'provider-opencode',
    systemPrompt: '你是 Tcode Swarm 的【架构终审与裁决仲裁者】。对照 PRD、设计规范与测试结果，做出权威审批裁决。',
    allowedTools: ['read_file'],
    readScopes: ['*'],
    writeScopes: [],
    maxConcurrency: 1,
    canDelegate: false
  },
  {
    id: 'agent-tech-writer',
    role: 'tech_writer',
    name: '技术文档与发布专家',
    avatar: '📝',
    description: '负责编写用户使用手册、API 文档、Changelog 发版日志与交付物归档。',
    category: 'product',
    modelId: 'opencode/mimo-v2-omni',
    providerId: 'provider-opencode',
    systemPrompt: '你是 Tcode Swarm 的【技术文档与发布专家】。为系统生成清晰、严谨的用户手册与发版日志。',
    allowedTools: ['write_file', 'read_file'],
    readScopes: ['*'],
    writeScopes: ['docs/**', 'README.md'],
    maxConcurrency: 2,
    canDelegate: false
  }
];

export function getBuiltinAgentByRole(role: AgentRole): AgentDefinition | undefined {
  return BUILTIN_AGENT_ROLES.find(a => a.role === role);
}
