use serde::{Deserialize, Serialize};
use tokio::time::{sleep, Duration};

/// Candidate output generated by Worker agents
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CandidateResult {
    pub worker_id: String,
    pub candidate_name: String,
    pub code_patch: String,
    pub execution_trace: String,
    pub is_empty: bool,
}

/// Review evaluation produced by the Streaming Review pipeline
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReviewFeedback {
    pub worker_id: String,
    pub reviewer_id: String,
    pub score: f32, // 0.0 - 1.0
    pub passed_syntax: bool,
    pub passed_unit_tests: bool,
    pub comments: String,
}

/// Final arbitration outcome
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArbiterDecision {
    pub selected_candidate: CandidateResult,
    pub confidence_score: f32, // 0.0 - 1.0
    pub is_confident: bool,    // >= 0.80 -> true
    pub human_reviewed: bool,
    pub rationale: String,
}

/// Swarm Flow Operators Execution Engine
pub struct SwarmFlowEngine;

impl SwarmFlowEngine {
    /// 1. Operator: budget()
    /// Inspect remaining token budget and concurrent workers capacity
    pub async fn budget(session_budget_tokens: u64) -> (u64, usize) {
        let workers_count = if session_budget_tokens > 20_000 {
            3
        } else if session_budget_tokens > 10_000 {
            2
        } else {
            1
        };
        (session_budget_tokens, workers_count)
    }

    /// 2. Operator: parallel()
    /// Launch Barrier Synchronization: all branches must complete before returning
    pub async fn parallel(
        task_prompt: &str,
        workers_count: usize,
    ) -> Vec<CandidateResult> {
        let mut handles = Vec::new();

        for i in 0..workers_count {
            let worker_id = format!("Worker-{}", (b'A' + i as u8) as char);
            let prompt = task_prompt.to_string();

            let handle = tokio::spawn(async move {
                // Simulate candidate generation
                sleep(Duration::from_millis(150 + (i as u64) * 50)).await;
                CandidateResult {
                    worker_id: worker_id.clone(),
                    candidate_name: format!("Candidate_{}", worker_id),
                    code_patch: format!("// Candidate implementation by {}\n// Task: {}\npub fn execute() -> bool {{ true }}\n", worker_id, prompt),
                    execution_trace: format!("{}: Observe -> Reason -> Act -> Verify passed", worker_id),
                    is_empty: false,
                }
            });
            handles.push(handle);
        }

        let mut candidates = Vec::new();
        for h in handles {
            if let Ok(c) = h.await {
                candidates.push(c);
            }
        }
        candidates
    }

    /// 3. Operator: compact()
    /// Remove empty branches and retain valid candidates only
    pub fn compact(candidates: Vec<CandidateResult>) -> Vec<CandidateResult> {
        candidates
            .into_iter()
            .filter(|c| !c.is_empty && !c.code_patch.trim().is_empty())
            .collect()
    }

    /// 4. Operator: pipeline()
    /// Streaming Review: each candidate advances as soon as its review is completed
    pub async fn pipeline(candidates: &[CandidateResult]) -> Vec<ReviewFeedback> {
        let mut reviews = Vec::new();
        for c in candidates {
            // Streaming review for candidate
            let score = if c.worker_id == "Worker-B" { 0.96 } else { 0.88 };
            reviews.push(ReviewFeedback {
                worker_id: c.worker_id.clone(),
                reviewer_id: "Reviewer-Pipeline-1".to_string(),
                score,
                passed_syntax: true,
                passed_unit_tests: true,
                comments: format!("Code quality score: {:.2}, verified without regression", score),
            });
        }
        reviews
    }

    /// 5. Operator: agent_session()
    /// Stateful Arbiter: persists state, aggregates candidates and reviewer feedback, selects best
    pub async fn agent_session(
        candidates: Vec<CandidateResult>,
        reviews: Vec<ReviewFeedback>,
    ) -> ArbiterDecision {
        let best_review = reviews
            .iter()
            .max_by(|a, b| a.score.partial_cmp(&b.score).unwrap());

        let best_worker_id = best_review
            .map(|r| r.worker_id.as_str())
            .unwrap_or("Worker-A");

        let best_score = best_review.map(|r| r.score).unwrap_or(0.90);

        let selected = candidates
            .into_iter()
            .find(|c| c.worker_id == best_worker_id)
            .unwrap_or_else(|| CandidateResult {
                worker_id: "Worker-Default".to_string(),
                candidate_name: "Candidate_Default".to_string(),
                code_patch: "".to_string(),
                execution_trace: "".to_string(),
                is_empty: false,
            });

        let is_confident = best_score >= 0.80;

        ArbiterDecision {
            selected_candidate: selected,
            confidence_score: best_score,
            is_confident,
            human_reviewed: false,
            rationale: format!(
                "Candidate [{}] chosen with highest review score {:.2}",
                best_worker_id, best_score
            ),
        }
    }

    /// 6. Operator: human()
    /// Human Fallback: triggered when arbiter confidence is insufficient
    pub async fn human(mut decision: ArbiterDecision, override_approval: bool) -> ArbiterDecision {
        if !decision.is_confident {
            decision.human_reviewed = true;
            if override_approval {
                decision.rationale.push_str(" · Human decision confirmed candidate");
            } else {
                decision.rationale.push_str(" · Human decision modified candidate");
            }
        }
        decision
    }

    /// 7. Operator: return
    /// Workflow output: final delivered result
    pub fn return_result(decision: ArbiterDecision) -> CandidateResult {
        decision.selected_candidate
    }

    /// Full Composed Swarm Flow Execution matching the blueprint:
    /// Task -> budget() -> Determine N -> parallel() -> compact() -> pipeline() -> agent_session() -> (Confident? Yes: return; No: human() -> return)
    pub async fn run_flow(task_prompt: &str, budget_tokens: u64) -> ArbiterDecision {
        // 1. budget()
        let (_remaining, workers_count) = Self::budget(budget_tokens).await;

        // 2. parallel()
        let candidates = Self::parallel(task_prompt, workers_count).await;

        // 3. compact()
        let valid_candidates = Self::compact(candidates);

        // 4. pipeline()
        let reviews = Self::pipeline(&valid_candidates).await;

        // 5. agent_session()
        let mut decision = Self::agent_session(valid_candidates, reviews).await;

        // 6. Confidence check -> human() fallback if needed
        if !decision.is_confident {
            decision = Self::human(decision, true).await;
        }

        decision
    }
}
